# docker build -t spotify-api:latest -f Dockerfile.prod .
# docker run --name spotify-api-run-1 -p 8000:8000 spotify-api:latest
# docker rm spotify-api-run-1
FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

CMD ["fastapi", "run", "app/main.py", "--port", "8000"]